[tool.poetry]
name = "ocsf-to-bq"
version = "0.1.0"
description = ""
authors = ["sMezaOrellana <s.g.meza.orellana@umail.leidenuniv.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
